Feat/exercise imc
adrianopratesr/estuding-js pull request #2
Opened 2023-08-19 06:52 UTC by adrianopratesr

este PR adiciona outros exercicios

2023-08-21 12:37 UTC, antoniomatiolijr requested changes

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise.js
> +let notas = [10, 15, 20];
`const grades`

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise.js
> +const mediaNotas = (nota) => {
`const calculateAverageGrades = (grades) =>`

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise.js
> +  );
É mais simples colocar o valor inicial direto, não precisa criar uma varíavel para isso. A não ser que seja diferente de zero (que é o comum)

```typescript

  const sumOfGrades = nota.reduce(
    (accumulator, currentValue) => accumulator + currentValue, 0);

```

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise.js
> +  return media;
Não precisa criar um outra variável, vc pode retornar direto.

```typescript

return sumOfGrades / grades.length;

```

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise2.js
> +let dolar = 10;
const value = 10;

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise3.js
> +let brl = 100;
amount

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise4.js
> +};
Assim vc pode receber a taxa que quiser na função

```typescript

const calculateAdjustmentRate = (value, TAX) => {
  return value * TAX;
};

```

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise5.js
> +let product = 100;
`value` ou `amount`

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise5.js
> +let readjustmentTax = 1.3333;
`const TAX = 1.3333;`

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise5.js
> +const readjustment = (product, readjustmentTax) => {
`calculateAdjustmentRate`

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise5.js
> +};
vc não precisa reatribuir o valor é só retornar direto.

```typescript
return product * readjustmentTax).toFixed(2)
```

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise6.js
> +let numberThree = 10;
const

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise7.js
> +let numberTwo = 15;
const

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise8.js
> +let ageFour = 13;
const

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios-js/exercise9.js
> +let temPasseEspecial = true;
const e variaveis em portugues

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios_base/exercise1.js
> +let cidade = "são josé dos campos";
const e variaveis em portugues

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios_base/exercise3.js
> +let b = 2;
const

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios_base/exercise3.js
> +const multiplicacao = (a, b) => {
multiply

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios_base/exercise4.js
> +let a = "adriano";
const

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios_base/exercise4.js
> +};
Capitalize é o ato de deixar a primeira maiuscula;

`const capitalize`

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios_base/exercise5.js
> +
ingles

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios_base/exercise5.js
> +const calcularIMC = (peso, altura) => {
calculate

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios_base/exercise5.js
> +  return imc;
return peso / (altura * altura)

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios_base/exercise5.js
> +const formatarIMC = (imc) => {
`format`

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios_base/exercise6.js
> +let a = 20;
const

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios_base/exercise6.js
> +const verificarIdade = (value) => {
verifyAge

2023-08-21 12:37 UTC, antoniomatiolijr commented on exercicios_base/exercise7.js
> +const validacaoFilme = (value) => {
Nome das funções deve descrever o que fazem um exemplo melhor é.

`classifyMovieByAge`

2023-08-21 12:37 UTC, antoniomatiolijr commented on imc-js/exercise-1.js
> +var altura = 1.5;
const

2023-08-21 12:37 UTC, antoniomatiolijr commented on imc-js/exercise-1.js
> +export function calcularIMC(peso, altura) {
calculate

2023-08-21 12:37 UTC, antoniomatiolijr commented on imc-js/exercise-1.js
> +  imc = peso / (altura * altura);
return peso / (altura * altura)

2023-08-21 12:37 UTC, antoniomatiolijr commented on imc-js/exercise-2.js
> +const calcular = (people) => {
coloca um nome melhor

2023-08-21 12:37 UTC, antoniomatiolijr commented on imc-js/exercise-2.js
> +    // console.log(`O IMC médio da lista é: ${calcularIMC}`);
remover essa parte

2023-08-21 12:37 UTC, antoniomatiolijr commented on imc-js/exercise-3.js
> +const calcular = (people) => {
aqui tb

2023-08-21 12:37 UTC, antoniomatiolijr commented on imc-js/exercise-4.js
> +const calcular = (people) => {
melhorar nome

2023-08-21 12:37 UTC, antoniomatiolijr commented on imc-js/exercise-5.js
> +const calcularMaior = (people) => {
aqui tb

2023-08-21 12:37 UTC, antoniomatiolijr commented on revisoes/revisao-2.js
> +let sym = Symbol("");
tudo const

2023-08-21 12:37 UTC, antoniomatiolijr commented on revisoes/revisao-3.js
> +};
breakStringInTwoLines

2023-08-21 12:37 UTC, antoniomatiolijr commented on revisoes/revisao-3.js
> +const data = () => {
aqui tb

2023-08-22 13:17 UTC, antoniomatiolijr requested changes

2023-08-22 13:17 UTC, antoniomatiolijr commented on exercicios-js/exercise.js
> +  );
`sumWithInitial` Não é um nome explicativo.

`sumOfGrades`

2023-08-22 13:17 UTC, antoniomatiolijr commented on exercicios-js/exercise3.js
> +  return (brl / DOLLAR_EXCHANGE).toFixed(2);
troca `brl` por `amount`

2023-08-22 13:17 UTC, antoniomatiolijr commented on exercicios-js/exercise4.js
> +const readjustment = (value, tax) => {
tax aqui é uma constante no conceito ou seja `TAX`, o value pode mudar

2023-08-22 13:17 UTC, antoniomatiolijr commented on exercicios-js/exercise5.js
> +const readjustment = (product, readjustmentrate) => {
`readjustmentRate` em camelCase (https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/JavaScript)

2023-08-22 13:17 UTC, antoniomatiolijr commented on exercicios-js/exercise9.js
> +  haveHelthCard,
hasHealthCard

2023-08-22 13:17 UTC, antoniomatiolijr commented on exercicios-js/exercise9.js
> +  accompaniedByAdult,
withAdult

2023-08-22 13:17 UTC, antoniomatiolijr commented on exercicios_base/exercise2.js
> +let b = "oi";
const

2023-08-22 13:17 UTC, antoniomatiolijr commented on exercicios_base/exercise5.js
> +};
tem que mudar aqui tb para ingles

2023-08-22 13:17 UTC, antoniomatiolijr commented on imc-js/exercise-1.js
> +  imc = peso / (altura * altura);
E colocar em ingles

2023-08-22 13:17 UTC, antoniomatiolijr commented on imc-js/exercise-2.js
> +const orderAlphabetically = (people) => {
orderByNameASC onde ASC significa (Ascending)

2023-08-22 13:17 UTC, antoniomatiolijr commented on imc-js/exercise-3.js
> +const descendingOrder = (people) => {
orderByIMCDESC

2023-08-22 13:17 UTC, antoniomatiolijr commented on imc-js/exercise-4.js
> +const calculingAverageIMC = (people) => {
calculateAverageIMC

2023-08-22 13:17 UTC, antoniomatiolijr commented on imc-js/exercise-4.js
> +  const qtdPessoas = people.length;
Em ingles

2023-08-22 13:17 UTC, antoniomatiolijr commented on imc-js/exercise-4.js
> +  let somaIMC = 0;
em ingles

2023-08-22 13:17 UTC, antoniomatiolijr commented on imc-js/exercise-4.js
> +    // console.log(`O IMC médio da lista é: ${calcularIMC}`);somaIMC / qtdPessoa
👀  apagar esse comentário

2023-08-22 13:17 UTC, antoniomatiolijr commented on imc-js/exercise-5.js
> +};
getHigherIMC

2023-08-22 13:17 UTC, antoniomatiolijr commented on imc-js/exercise-5.js
> +const lowerIMC = (people) => {
getLowerIMC

2023-08-22 13:17 UTC, antoniomatiolijr commented on imc-js/exercise-5.js
> +// quais são as principais funções de interadores?
remover daqui

2023-08-22 13:17 UTC, antoniomatiolijr commented on revisoes/revisao-3.js
> +};
formatCurrentDate

2023-08-22 13:17 UTC, antoniomatiolijr commented on revisoes/revisao-3.js
> +const dataA = new Date(23, 8, 19);
dateA, dateB

2023-08-22 13:17 UTC, antoniomatiolijr commented on revisoes/revisao-3.js
> +  const dataC = valueA - valueB;
difference

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise.js
> +let notas = [10, 15, 20];
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise.js
> +const mediaNotas = (nota) => {
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise.js
> +  );
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise.js
> +  return media;
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise2.js
> +let dolar = 10;
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise3.js
> +let brl = 100;
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise4.js
> +};
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise5.js
> +let product = 100;
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise5.js
> +let readjustmentTax = 1.3333;
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise5.js
> +const readjustment = (product, readjustmentTax) => {
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise5.js
> +};
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise6.js
> +let numberThree = 10;
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise7.js
> +let numberTwo = 15;
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise8.js
> +let ageFour = 13;
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios-js/exercise9.js
> +let temPasseEspecial = true;
feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios_base/exercise1.js
> +let cidade = "são josé dos campos";
feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios_base/exercise3.js
> +let b = 2;
feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios_base/exercise3.js
> +const multiplicacao = (a, b) => {
feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios_base/exercise4.js
> +let a = "adriano";
feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios_base/exercise4.js
> +};
feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios_base/exercise5.js
> +
feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios_base/exercise5.js
> +const calcularIMC = (peso, altura) => {
feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios_base/exercise5.js
> +  return imc;
feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios_base/exercise5.js
> +const formatarIMC = (imc) => {
feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios_base/exercise6.js
> +let a = 20;
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios_base/exercise6.js
> +const verificarIdade = (value) => {
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on exercicios_base/exercise7.js
> +const validacaoFilme = (value) => {
feito

2023-08-22 13:20 UTC, adrianopratesr commented on imc-js/exercise-1.js
> +var altura = 1.5;
Tirei pois nao precisamos usar

2023-08-22 13:20 UTC, adrianopratesr commented on imc-js/exercise-1.js
> +  imc = peso / (altura * altura);
Se eu retornar desta maneira quando eu realizo um console.log para me retornar valor formatado não teria que ficar desta maneira
console.log(formartTextImc(calculate(peso, altura)))
hoje quando eu guardo em uma variavel fica assim
console.log(formartTextImc(imc))

qual a melhor forma neste caso?

2023-08-22 13:20 UTC, adrianopratesr commented on imc-js/exercise-2.js
> +const calcular = (people) => {
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on imc-js/exercise-2.js
> +    // console.log(`O IMC médio da lista é: ${calcularIMC}`);
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on imc-js/exercise-3.js
> +const calcular = (people) => {
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on imc-js/exercise-4.js
> +const calcular = (people) => {
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on imc-js/exercise-5.js
> +const calcularMaior = (people) => {
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on revisoes/revisao-2.js
> +let sym = Symbol("");
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on revisoes/revisao-3.js
> +};
Feito

2023-08-22 13:20 UTC, adrianopratesr commented on revisoes/revisao-3.js
> +const data = () => {
Feito

2023-08-27 21:11 UTC, antoniomatiolijr requested changes

2023-08-27 21:11 UTC, antoniomatiolijr commented on imc-js/exercise-4.js
> +  const qtdPeople = people.length;
Em inglês

2023-08-28 03:39 UTC, antoniomatiolijr requested changes

2023-08-28 03:39 UTC, antoniomatiolijr commented on revisoes/revisao-3.js
> +const displayingDateInformation = (date) => {
`showDateDetails` Sempre colocamos um verbo pois uma função deve representar uma ação

2023-08-28 03:39 UTC, antoniomatiolijr commented on revisoes/revisao-3.js
> +  ];
como podemos usar essas constantes em outras funções vcs podem externalizar isso.

E lembrem se isso são constantes de fato então. `WEEK_DAYS` e `MONTHS_IN_PTBR`

2023-08-28 20:54 UTC, antoniomatiolijr approved these changes

2023-08-29 01:18 UTC, merged